use b2b;
set names utf8;

create table product(
    id mediumint(8) unsigned not null auto_increment primary key comment '序号',
    corpid mediumint(8) unsigned not null default 0 comment '公司id',
    corpname varchar(100) not null default '' comment '公司名称',
    productName varchar(100) not null default '' comment '产品名称',
    detail text comment '详细说明',
    expire int(11) not null default 0 comment '信息有效期',
    pic varchar(100) not null default '' comment '上传图片',
    measureUnit  tinyint(4) not null default 0 comment '计量单位',
    productPrice  varchar(100) not null default '' comment '产品单价',
    minAmount  varchar(100) not null default '' comment '最小起订量',
    totalAmount  varchar(100) not null default '' comment '供货总量',
    deliverDate  varchar(100) not null default '' comment '发货期限',
    
    brief  varchar(100) not null default '' comment '简介',
    keyword varchar(100) not null default '' comment '关键词',
    title varchar(100) not null default '' comment '信息标题',
    
    category1 mediumint(8) unsigned not null default 0 comment '产品行业',
    category2 mediumint(8) unsigned not null default 0 comment '产品行业',
    category3 mediumint(8) unsigned not null default 0 comment '产品行业',
    
    key(corpid),
    key(expire),
    key(category1),
    key(category2),
    key(category3)
)engine=myisam default charset=utf8 collate=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `company` (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT COMMENT '序号',
  `username` varchar(20) NOT NULL DEFAULT '' COMMENT '会员登录名',
  `password` varchar(32) NOT NULL DEFAULT '123456' COMMENT '密码',
  `corpname` varchar(100) NOT NULL DEFAULT '' COMMENT '公司名称',
  `corptype` tinyint(4) NOT NULL DEFAULT '0' COMMENT '企业类型',
  `corpintro` varchar(200) NOT NULL DEFAULT '' COMMENT '公司简介',
  `registerPlace` varchar(100) NOT NULL DEFAULT '' COMMENT '公司注册地',
  `capitial` tinyint(4) unsigned NOT NULL DEFAULT '0' COMMENT '注册资本',
  `capitalUnit` varchar(40) NOT NULL DEFAULT '' COMMENT '资本单位',
  `categories` varchar(100) NOT NULL DEFAULT '' COMMENT '主营行业',
  `logo` varchar(100) NOT NULL DEFAULT '' COMMENT '企业logo',
  `pic` varchar(100) NOT NULL DEFAULT '' COMMENT '公司图片',
  `realname` varchar(20) NOT NULL COMMENT '业务联系人',
  `sex` varchar(4) NOT NULL DEFAULT '先生' COMMENT '性别',
  `tel` varchar(20) NOT NULL DEFAULT '' COMMENT '公司电话',
  `fax` varchar(20) NOT NULL DEFAULT '' COMMENT '传真',
  `email` varchar(100) NOT NULL DEFAULT '' COMMENT '电子邮箱',
  `province` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT '省份',
  `city` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT '城市',
  `address` varchar(100) NOT NULL DEFAULT '' COMMENT '公司地址',
  `zipCode` varchar(6) NOT NULL DEFAULT '' COMMENT '邮政编码',
  `dept` varchar(20) NOT NULL DEFAULT '' COMMENT '部门',
  `job` varchar(20) NOT NULL DEFAULT '' COMMENT '职位',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '手机',
  `website` varchar(100) NOT NULL DEFAULT '#' COMMENT '公司网址',
  `msn` varchar(100) NOT NULL DEFAULT '' COMMENT 'msn',
  `qq` varchar(20) NOT NULL DEFAULT '' COMMENT 'qq',
  `setupTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '公司成立时间',
  `registerNumber` varchar(50) NOT NULL DEFAULT '' COMMENT '公司注册号',
  `taxRegNo` varchar(50) NOT NULL DEFAULT '' COMMENT '税务注册号',
  `manageTime` varchar(50) NOT NULL DEFAULT '' COMMENT '营业期限',
  `manageBound` varchar(200) NOT NULL DEFAULT '' COMMENT '经营范围',
  `registerOrgan` varchar(40) NOT NULL DEFAULT '' COMMENT '登记机关',
  `checkTime` tinyint(4) NOT NULL DEFAULT '0' COMMENT '最近年检时间',
  `artificialPerson` varchar(10) NOT NULL DEFAULT '' COMMENT '法人',
  `numberOfEmployee` varchar(20) NOT NULL DEFAULT '' COMMENT '员工人数',
  `manageMode` varchar(20) NOT NULL DEFAULT '' COMMENT '经营模式',
  `brand` varchar(40) NOT NULL DEFAULT '' COMMENT '品牌名称',
  `manageArea` varchar(40) NOT NULL DEFAULT '' COMMENT '主要经营地点',
  `primaryMarket` varchar(200) NOT NULL DEFAULT '' COMMENT '主要市场',
  `primaryCustomers` varchar(40) NOT NULL DEFAULT '' COMMENT '主要客户群',
  `turnover` varchar(40) NOT NULL DEFAULT '' COMMENT '年营业额',
  `exportAmount` varchar(40) NOT NULL DEFAULT '' COMMENT '年出口额',
  `importAmount` varchar(40) NOT NULL DEFAULT '' COMMENT '年进口额',
  `accountBank` varchar(40) NOT NULL DEFAULT '' COMMENT '开户银行',
  `account` varchar(40) NOT NULL DEFAULT '' COMMENT '帐号',
  `monthOutput` varchar(40) NOT NULL DEFAULT '' COMMENT '月产量',
  `workshopArea` varchar(40) NOT NULL DEFAULT '' COMMENT '厂房面积',
  `providerOEM` varchar(40) NOT NULL DEFAULT '' COMMENT '是否提供OEM代加工？',
  `authType` varchar(100) NOT NULL DEFAULT '' COMMENT '管理体系认证',
  `qualityControl` varchar(40) NOT NULL DEFAULT '' COMMENT '质量控制',
  `ts` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`)
)engine=myisam default charset=utf8 collate=utf8_general_ci; 